### ISSUE TITLE
new user with records assigned to, makes the portal error at login and crashes it

### ISSUE THREAD

**Issue by moisbo** [redbox-mint/redbox-portal#532]
If a user that logs in via AAF has records in the database associated to their email/permissions, the redbox-portal crashes with 500 error

(**In vagrant**) Steps to reproduce:

- deleteDBs (delete all records from database)
![screen shot 2019-02-12 at 10 13 41 am](https://user-images.githubusercontent.com/2850269/52600181-e7d20a00-2eae-11e9-93f4-1deaedbb32e8.png)

- wait for start
- login as admin
- create rdmp
- add FNCI and DataManager someone different than the Admin
![screen shot 2019-02-12 at 10 15 09 am](https://user-images.githubusercontent.com/2850269/52600248-19e36c00-2eaf-11e9-9424-8829db29a5a4.png)
- save
- login with AAF
portal error
```
redbox-portal_redboxportal_1 exited with code 1
```
and in
redbox-storage
```
2019-02-11 23:17:07,355          ERROR  ebServiceApplication Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:539) ~[org.restlet-2.3.7.jar:na]
	at org.restlet.resource.ServerResource.get(ServerResource.java:742) ~[org.restlet-2.3.7.jar:na]
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:617) ~[org.restlet-2.3.7.jar:na]
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:678) ~[org.restlet-2.3.7.jar:na]
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:356) ~[org.restlet-2.3.7.jar:na]
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1043) ~[org.restlet-2.3.7.jar:na]
	at org.restlet.resource.Finder.handle(Finder.java:236) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202) [org.restlet-2.3.7.jar:na]
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77) [org.restlet-2.3.7.jar:na]
	at org.restlet.Application.handle(Application.java:385) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.7.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.7.jar:na]
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202) [org.restlet-2.3.7.jar:na]
	at org.restlet.Component.handle(Component.java:408) [org.restlet-2.3.7.jar:na]
	at org.restlet.Server.handle(Server.java:507) [org.restlet-2.3.7.jar:na]
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63) [org.restlet-2.3.7.jar:na]
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143) [org.restlet-2.3.7.jar:na]
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117) [org.restlet.ext.servlet-2.3.7.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) [servlet-api-2.5-20081211.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166) [jetty-6.1.24.jar:6.1.24]
	at org.apache.tapestry5.TapestryFilter.doFilter(TapestryFilter.java:171) [tapestry-core-5.4.1.jar:na]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126) [jetty-6.1.24.jar:6.1.24]
	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:195) [urlrewritefilter-3.1.0.jar:3.1.0]
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:159) [urlrewritefilter-3.1.0.jar:3.1.0]
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:141) [urlrewritefilter-3.1.0.jar:3.1.0]
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:90) [urlrewritefilter-3.1.0.jar:3.1.0]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:417) [urlrewritefilter-3.1.0.jar:3.1.0]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [jetty-6.1.24.jar:6.1.24]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at com.googlecode.fascinator.portal.security.filter.FascinatorAuthenticationInterceptorFilter.doFilterInternal(FascinatorAuthenticationInterceptorFilter.java:138) [fascinator-portal-1.6-SNAPSHOT-classes.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at com.googlecode.fascinator.portal.security.filter.FascinatorOwaspInterceptorFilter.doFilterInternal(FascinatorOwaspInterceptorFilter.java:62) [fascinator-portal-1.6-SNAPSHOT-classes.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [spring-security-web-3.2.10.RELEASE.jar:na]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410) [jetty-6.1.24.jar:6.1.24]
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [jetty-util-6.1.24.jar:6.1.24]
Caused by: com.googlecode.fascinator.api.storage.StorageException: Error; Null PID recieved
	at au.com.redboxresearchdata.fascinator.storage.mongo.MongoDigitalObject.getPayload(MongoDigitalObject.java:282) ~[plugin-storage-mongo-1.0.1-SNAPSHOT.jar:na]
	at com.googlecode.fascinator.redbox.ws.v1.resources.RecordMetadataResource.getMetadataResource(RecordMetadataResource.java:53) ~[redbox-web-service-1.2-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:523) ~[org.restlet-2.3.7.jar:na]
	... 110 common frames omitted
```

**Comment by andrewbrazzatti** [comment]
Hey @moisbo,

Can you attach a screenshot of what the `db.getCollection('rdmp').find({})` looks like after you've created the record with admin and before the AAF user logs in?

**Comment by moisbo** [comment]
Sure thing.

```
{
    "metaMetadata" : {
        "brandId" : "5c622093bebd600006c46597",
        "createdBy" : "admin",
        "type" : "rdmp",
        "form" : "default-1.0-draft"
    },
    "authorization" : {
        "view" : [],
        "edit" : [],
        "viewRoles" : [ 
            "Admin", 
            "Librarians"
        ],
        "editRoles" : [ 
            "Admin", 
            "Librarians"
        ],
        "editPending" : [ 
            "Moises.Sacal@uts.edu.au"
        ],
        "viewPending" : [ 
            "Moises.Sacal@uts.edu.au"
        ]
    },
    "metadata" : {
        "" : {},
        "title" : "Contact zones: activism, art and media in Italy, 1994-2006",
        "dc:identifier" : "100001797",
        "description" : "The last decade in Italy has seen the proliferation of innovative activist practices resulting from a productive traffic between political theory with art and media. Merging with activism, art and media practices take a dynamic role in the promotion of social change while simultaneously providing a critical commentary to social and political issues in contemporary Italy. This research, which will result in a book length study, will be the first to explore the emergence of contact zones in these practices. ",
        "finalKeywords" : [ 
            "Italy", 
            "Social change", 
            "Activism", 
            "Contemporary art", 
            "Media", 
            "Politics"
        ],
        "dc:relation_bibo:Website" : "",
        "dc:coverage_vivo:DateTimeInterval_vivo:start" : "",
        "dc:coverage_vivo:DateTimeInterval_vivo:end" : "",
        "foaf:fundedBy_foaf:Agent" : [ 
            ""
        ],
        "foaf:fundedBy_vivo:Grant" : [ 
            ""
        ],
        "dc:subject_anzsrc:for" : [],
        "dc:subject_anzsrc:seo" : "",
        "contributor_ci" : {
            "text_full_name" : "Moises Sacal Bonequi",
            "full_name_honorific" : "Mr Moises Sacal Bonequi",
            "email" : "Moises.Sacal@uts.edu.au",
            "given_name" : "Moises",
            "family_name" : "Sacal Bonequi",
            "honorific" : "Mr",
            "full_name_family_name_first" : "Moises, Sacal Bonequi",
            "username" : "",
            "role" : "Chief Investigator"
        },
        "contributor_data_manager" : {
            "text_full_name" : "Moises Sacal Bonequi",
            "full_name_honorific" : "Mr Moises Sacal Bonequi",
            "email" : "Moises.Sacal@uts.edu.au",
            "given_name" : "Moises",
            "family_name" : "Sacal Bonequi",
            "honorific" : "Mr",
            "full_name_family_name_first" : "Moises, Sacal Bonequi",
            "username" : "",
            "role" : "Data manager"
        },
        "contributors" : [ 
            {
                "full_name_honorific" : "",
                "given_name" : "",
                "family_name" : "",
                "honorific" : "",
                "full_name_family_name_first" : "",
                "username" : "",
                "role" : "Contributors"
            }
        ],
        "contributor_supervisor" : {
            "full_name_honorific" : "",
            "given_name" : "",
            "family_name" : "",
            "honorific" : "",
            "full_name_family_name_first" : "",
            "username" : "",
            "role" : "Supervisor"
        },
        "vivo:Dataset_redbox:DataCollectionMethodology" : "admin-test",
        "vivo:Dataset_dc_format" : "admin-test",
        "vivo:Dataset_redbox:DataCollectionResources" : "",
        "vivo:Dataset_redbox:DataAnalysisResources" : "",
        "vivo:Dataset_redbox:MetadataStandard" : "",
        "vivo:Dataset_redbox:DataStructureStandard" : "",
        "redbox:retentionPeriod_dc:date" : "permanent",
        "redbox:retentionPeriod_dc:date_skos:note" : "",
        "dataowner_name" : "Moises Sacal Bonequi",
        "dataowner_email" : "Moises.Sacal@uts.edu.au",
        "dc:rightsHolder_dc:name" : "student",
        "dc:rightsHolder_dc:description" : "",
        "redbox:ContractualObligations" : "",
        "dc:accessRights" : "by permission from the data manager",
        "dataLicensingAccess_manager" : "Moises Sacal Bonequi",
        "agls:protectiveMarking_dc:type" : [],
        "agls:policy_dc:identifier" : "",
        "agls:policy_skos:note" : "",
        "dc:coverage_dc:identifier" : [ 
            ""
        ],
        "agls:protectiveMarking_skos:note" : "",
        "grant_number_name" : "",
        "workspaces" : [],
        "WorkspaceSelector" : "",
        "vivo:Dataset_dc:location_rdf:PlainLiteral" : "",
        "vivo:Dataset_dc:location_skos:note" : "",
        "@context" : {
            "title" : "http://purl.org/dc/elements/1.1/title",
            "description" : "http://purl.org/dc/elements/1.1/description",
            "startDate" : "http://schema.org/Date",
            "endDate" : "http://schema.org/Date"
        }
    },
    "workflow" : {
        "stage" : "draft",
        "stageLabel" : ""
    },
    "redboxOid" : "70a775a1bd1b27173544e8341cc56162",
    "packageType" : [ 
        "rdmp"
    ],
    "date_object_created" : [ 
        "2019-02-12T01:27:48.535Z"
    ],
    "date_object_modified" : [ 
        "2019-02-12T01:27:48.553Z"
    ]
}
```
